[build]
  command = "npm run build"
  functions = "functions"
[[redirects]]
  from = "/api/*"
  to = "http://localhost:8800/:splat"
  status = 200

[dev]
  command = "npm start"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
